### 1.  Multi Indexing also known as Heirarchical Indexing 
### 2. MultiIndexing also used form converting high dimension to lower dimension 
### 3.  how to create multiIndexing Series :
#### - pd.MultiIndex.from_tuple()
#### - pd.MultiIndex.from_product()
#### - levels
#### - levels[0] --> only apply on index 
#### - 1. stack()  > df to series  $$$ column  ke last level ko  >  row  ke last level mai change karne ke liye use hota hai .

#### - 2. unstack() > series to df   $$$  row  ke last level ko > column ke last level mai change karne ke liye use hota hai 
#### -

# Working with MultiIndex DataFrames :
1. .head()/ tail()
2. .shape
3. .info()
4. .isnull()
5. .duplicated()
6. .loc[]
7. .iloc[]
8. .sort_index(level = , ascending = [False,True ])
9. .transpose()
10. .swaplevel(axis = 0 )  >> works only on heirarchical axis .
11. .melt() -> convert 'wide' format to -> 'long' format .
12. .melt(var_name=  , value_name = )
13.  after melt().stack() >>
14. .melt(id_vars = [col1 , col2 , col3 ], var_name=  , value_name = )
15. id_vars => jo columns base ke basee he choldne ho

### Wide Format :
- wide format is where , we have a single row for every datapoint with multiple columns to hold the values of various attributes .

### Long Format : 
- In a long format (also called tidy or stacked data), each row represents a single observation or datapoint. Instead of spreading different variables across multiple columns, you compress them into key-value pairs across multiple rows.

In [70]:
import numpy as np 
import pandas as pd

In [71]:
index = [(12, 'esc'),(13,'ecs'),(14,'ecs'), (15,'cse'), (16,'cse'),(17,'cse')]

In [72]:
name = ['Ranish', "Gargi","Samradhi","Puja","ritu","Jigyasa"]

In [73]:
pd.Series(name , index = index)

(12, esc)      Ranish
(13, ecs)       Gargi
(14, ecs)    Samradhi
(15, cse)        Puja
(16, cse)        ritu
(17, cse)     Jigyasa
dtype: str

In [74]:
multi_index = pd.MultiIndex.from_tuples(index)

In [75]:
multi_index.levels[0]

Index([12, 13, 14, 15, 16, 17], dtype='int64')

In [76]:
s1 = pd.Series(name , index = multi_index)

In [77]:
m_i = pd.MultiIndex.from_product([['cse', 'ecs'],[12 , 13 ,14 ]] )

In [78]:
m_i

MultiIndex([('cse', 12),
            ('cse', 13),
            ('cse', 14),
            ('ecs', 12),
            ('ecs', 13),
            ('ecs', 14)],
           )

In [79]:
s2 = pd.Series(name , index = m_i)

In [80]:
s2

cse  12      Ranish
     13       Gargi
     14    Samradhi
ecs  12        Puja
     13        ritu
     14     Jigyasa
dtype: str

In [81]:
series_to_df = s2.unstack()

In [82]:
series_to_df

         12     13        14
cse  Ranish  Gargi  Samradhi
ecs    Puja   ritu   Jigyasa

In [83]:
df_to_series = series_to_df.stack()

In [84]:
df_to_series

cse  12      Ranish
     13       Gargi
     14    Samradhi
ecs  12        Puja
     13        ritu
     14     Jigyasa
dtype: str

# MultiIndex DataFrame :

In [85]:
df = pd.DataFrame([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]],index = m_i, columns = ['odd', 'even'])

In [86]:
#  rows 
df.iloc[0 : 4 ]

        odd  even
cse 12    1     2
    13    3     4
    14    5     6
ecs 12    7     8

In [87]:
df.loc['cse']

    odd  even
12    1     2
13    3     4
14    5     6

In [88]:
df.loc['ecs']

    odd  even
12    7     8
13    9    10
14   11    12

In [89]:
df['odd']

cse  12     1
     13     3
     14     5
ecs  12     7
     13     9
     14    11
Name: odd, dtype: int64

In [90]:
df['even']

cse  12     2
     13     4
     14     6
ecs  12     8
     13    10
     14    12
Name: even, dtype: int64

### MultiIndexing from columns perspectives :

#### (i). MultiIndexing in term of columns :

In [91]:
import pandas as pd

df2 = pd.DataFrame(
    [
        [1, 2, 3, 4],       # Added 4th column values
        [5, 6, 7, 8], 
        [9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]
    ],
    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    columns=pd.MultiIndex.from_product([['delhi', 'mumbai'], ['package', 'student_id']])
)
df2

     delhi             mumbai
   package student_id package student_id
1        1          2       3          4
2        5          6       7          8
3        9         10      11         12
4       13         14      15         16
5       17         18      19         20
6       21         22      23         24
7       25         26      27         28
8       29         30      31         32
9       33         34      35         36
10      37         38      39         40

In [92]:
df2['delhi']['package']

1      1
2      5
3      9
4     13
5     17
6     21
7     25
8     29
9     33
10    37
Name: package, dtype: int64

In [93]:
df2.loc[3]

delhi   package        9
        student_id    10
mumbai  package       11
        student_id    12
Name: 3, dtype: int64

In [94]:
df_to_s = df2.unstack()

In [95]:
df_to_s

delhi   package     1      1
                    2      5
                    3      9
                    4     13
                    5     17
                    6     21
                    7     25
                    8     29
                    9     33
                    10    37
        student_id  1      2
                    2      6
                    3     10
                    4     14
                    5     18
                    6     22
                    7     26
                    8     30
                    9     34
                    10    38
mumbai  package     1      3
                    2      7
                    3     11
                    4     15
                    5     19
                    6     23
                    7     27
                    8     31
                    9     35
                    10    39
        student_id  1      4
                    2      8
                    3     12
                    4     16
                    5     20
                    6     24
                    7     28
                    8     32
                    9     36
                    10    40
dtype: int64

In [96]:
s_to_df = df2.stack()

In [97]:
s_to_df

               delhi  mumbai
1  package         1       3
   student_id      2       4
2  package         5       7
   student_id      6       8
3  package         9      11
   student_id     10      12
4  package        13      15
   student_id     14      16
5  package        17      19
   student_id     18      20
6  package        21      23
   student_id     22      24
7  package        25      27
   student_id     26      28
8  package        29      31
   student_id     30      32
9  package        33      35
   student_id     34      36
10 package        37      39
   student_id     38      40

In [111]:
df2.iloc[0]

delhi   package       1
        student_id    2
mumbai  package       3
        student_id    4
Name: 1, dtype: int64

In [113]:
df2.sort_index(level = 0 , ascending= False)

     delhi             mumbai
   package student_id package student_id
10      37         38      39         40
9       33         34      35         36
8       29         30      31         32
7       25         26      27         28
6       21         22      23         24
5       17         18      19         20
4       13         14      15         16
3        9         10      11         12
2        5          6       7          8
1        1          2       3          4

In [114]:
df2.transpose()

                   1   2   3   4   5   6   7   8   9   10
delhi  package      1   5   9  13  17  21  25  29  33  37
       student_id   2   6  10  14  18  22  26  30  34  38
mumbai package      3   7  11  15  19  23  27  31  35  39
       student_id   4   8  12  16  20  24  28  32  36  40

In [119]:
df2.swaplevel(axis = 1)

   package student_id package student_id
     delhi      delhi  mumbai     mumbai
1        1          2       3          4
2        5          6       7          8
3        9         10      11         12
4       13         14      15         16
5       17         18      19         20
6       21         22      23         24
7       25         26      27         28
8       29         30      31         32
9       33         34      35         36
10      37         38      39         40

In [121]:
pd.DataFrame({'cse':[120]})

   cse
0  120

In [122]:
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [127]:
pd.DataFrame({'cse':[120],'ecse':[121],'ecse':[122],'ecse':[123]}).melt(var_name = 'branch', value_name ='num_students').

  branch  num_students
0    cse           120
1   ecse           123

In [126]:
confirmed  = pd.read_csv(r"C:\Users\HOME\Downloads\time_series_covid19_confirmed_global.csv")
deaths = pd.read_csv(r"C:\Users\HOME\Downloads\time_series_covid19_deaths_global.csv")

In [128]:
confirmed

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,703228,703228,703228,703228,703228,703228,703228,703228,703228,703228
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,11945
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,334021,334021,334066,334108,334196,334294,334425,334425,334629,334661
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,259981,259981,259981,259981,259981,259981,259981,259981,259981,259981

In [129]:
deaths

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5708,5708,5708,5708,5708,5708,5708,5708,5708,5708
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2159,2159,2159,2159,2159,2159,2159,2159,2159,2159
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,4019,4019,4022,4022,4023,4023,4024,4024,4024,4024
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5637,5637,5637,5637,5637,5637,5637,5637,5637,5637

In [136]:
deaths = deaths.melt(
    id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'],
    var_name='date', 
    value_name='num_deaths'  # Changed from 'nums_date' to a unique name
)

In [137]:
deaths

,Province/State,Country/Region,Lat,Long,date,num_deaths
0,NaN,Afghanistan,33.939110,67.709953,date,1/22/20
1,NaN,Albania,41.153300,20.168300,date,1/22/20
2,NaN,Algeria,28.033900,1.659600,date,1/22/20
3,NaN,Andorra,42.506300,1.521800,date,1/22/20
4,NaN,Angola,-11.202700,17.873900,date,1/22/20
...,...,...,...,...,...,...
622501,NaN,West Bank and Gaza,31.952200,35.233200,nums_date,5708
622502,NaN,Winter Olympics 2022,39.904200,116.407400,nums_date,0
622503,NaN,Yemen,15.552727,48.516388,nums_date,2159
622504,NaN,Zambia,-13.133897,27.849332,nums_date,4024
622505,NaN,Zimbabwe,-19.015438,29.154857,nums_date,5637

In [138]:
confirmed = confirmed.melt(
    id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'],
    var_name='date', 
    value_name='num_deaths'  # Changed from 'nums_date' to a unique name
)

In [139]:
confirmed

,Province/State,Country/Region,Lat,Long,date,num_deaths
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981